# Generated by Django 5.1.5 on 2025-01-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0003_productcategory_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='supplier',
        ),
    ]
