# Generated by Django 5.1.5 on 2025-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0004_remove_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
