# Generated by Django 5.1.5 on 2025-01-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0008_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
