# Generated by Django 5.1.5 on 2025-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0009_remove_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0.0004950495049504951),
            preserve_default=False,
        ),
    ]
