# Generated by Django 5.1.5 on 2025-01-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0015_size_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
