# Generated by Django 5.1.6 on 2025-02-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0018_productupdaterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productupdaterequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productupdaterequest',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productupdaterequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productupdaterequest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productupdaterequest',
            name='stock',
        ),
    ]
