# Generated by Django 5.1.6 on 2025-03-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0022_remove_order_status_order_payment_order_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotInteraction',
        ),
    ]
